# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startPage', '0005_project_project_contents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='big_project_name',
        ),
    ]
