# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-05 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startPage', '0006_auto_20170727_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='project_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
