# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-05 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startPage', '0007_issue_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='create',
        ),
    ]
