# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startPage', '0007_auto_20170804_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brain_storm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=40)),
                ('ideas', models.TextField()),
            ],
        ),
    ]
