# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startPage', '0008_brain_storm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brain_storm',
            new_name='Brainstorm',
        ),
    ]
